@startuml
Actor CampusManager
activate CampusManager

CampusManager -> UI : Asks to create a building floor
activate UI
UI --> CampusManager : requests data(buildingId, floorNumber, Description)
deactivate UI
CampusManager -> UI : types requested data (buildingId, floorNumber, Descriptio)
activate UI
UI --> CampusManager : informs operation success
deactivate UI

@enduml