@startuml
Actor User
activate User

User -> UI : Requests a list of the buildings with the minimum and the maximum floors
activate UI
UI --> User : returns a list of the buildings with the minimum and the maximum floors
deactivate UI

@enduml