@startuml 
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US380

actor "Fleet Manager" as GM
participant "<<System>> <<Context C4>> RobDroneGo" as Sys

activate GM

GM -> Sys: Request to view all existing robots 
activate Sys

Sys --> GM: Shows robot list
deactivate Sys


@enduml
