@startuml
autonumber

Actor FleetManager
activate FleetManager
FleetManager -> SPA : Asks to create a robot type
activate SPA

SPA --> FleetManager : requests data (robotTypeId, code, brand, model, taskTypes)
deactivate SPA

FleetManager -> SPA : types requested data (robotTypeId, code, brand, model, taskTypes)
activate SPA

SPA -> RobotType : POST/robotType(robotTypeId, code, brand, model, taskTypes)
activate RobotType

RobotType --> SPA : status code
deactivate RobotType

alt successfull case
    SPA -> FleetManager: robot type created successfully
else failure
    SPA -> FleetManager: robot type not created
end


@enduml