@startuml

actor SystemUser
activate SystemUser
SystemUser -> UI : Requests a task intending the necessary parameters for its execution
activate UI
UI --> SystemUser : requests data (string pickupPlace, string deliveryPlace, string pickupPersonName, string pickupPersonPhoneNumber, string deliveryPersonName, string deliveryPersonPhoneNumber, string description, string confirmationCode, TasksStatus status)
deactivate UI
SystemUser -> UI : types requested data (string pickupPlace, string deliveryPlace, string pickupPersonName, string pickupPersonPhoneNumber, string deliveryPersonName, string deliveryPersonPhoneNumber, string description, string confirmationCode, TasksStatus status)
activate UI
UI --> SystemUser : informs operation result
deactivate UI



@enduml