@startuml

activate SPA
SPA -> GestaoInfoAPI : get(/api/floors)
activate GestaoInfoAPI

GestaoInfoAPI -> FloorController : get
activate FloorController

FloorController -> FloorService : listFloors()
activate FloorService

FloorService -> BuildingRepo : findByDomainId(floor)
activate BuildingRepo

BuildingRepo --> FloorService : building
deactivate BuildingRepo

loop
    FloorService -> FloorRepo : get
    activate FloorRepo

    FloorRepo --> FloorService : floor
    deactivate FloorRepo

    FloorService -> FloorMapper : toDTO(floor)
    activate FloorMapper

    FloorMapper --> FloorService : floorDTO
    deactivate FloorMapper

    FloorService -> FloorService : list.push(floorDTO)
end

FloorService --> FloorController : floorDTO[ ]
deactivate FloorService

FloorController --> GestaoInfoAPI : status code 201
deactivate FloorController

GestaoInfoAPI --> SPA : success
deactivate GestaoInfoAPI

deactivate SPA

@enduml