@startuml
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US170

actor "User" as User
participant "UI" as UI   

activate User
activate UI
User -> UI : 1 : requests all buildings with min and max floors
UI --> User : returns json with buildings sorted by min and max floors


@enduml