@startuml
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US270

actor "User" as User
participant "UI" as UI

activate User

User -> UI : asks to create an elevator on a building
activate UI
UI --> User : requests data (building, elevatorCode, listFloors, brand, model, serialNumber, description, location)
deactivate UI
User -> UI : provides the required data
activate UI
UI --> User : shows confirmation and new elevator info
deactivate UI

@enduml