@startuml
Actor User
activate User

User -> UI : Asks to create a passageway between buildings
activate UI
UI --> User : requests data for the first building (buildingId)
deactivate UI
User -> UI : types requested data (buildingId)
activate UI
UI --> User : requests data for the second building (buildingId)
deactivate UI
User -> UI : types requested data (buildingId)
activate UI
UI --> User : informs operation success
deactivate UI


@enduml