@startuml

activate SPA
SPA -> GestaoInfoAPI : (api/systemUser)
activate GestaoInfoAPI
GestaoInfoAPI -> SystemUserController : delete
activate SystemUserController
SystemUserController -> SystemUserService : removeSystemUser()
activate SystemUserService

SystemUserService -> SystemUser : remove
SystemUserService -> SystemUserRepo : remove(systemUser)

SystemUserController -> GestaoInfoAPI : status code 201

GestaoInfoAPI -> SPA : Success

@enduml