@startuml

skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US1200

actor "Campus Manager" as User
participant "UI" as UI

activate User
User -> UI : Requests a list of the building floors with a passage to another building
activate UI
UI --> User : returns a list of the building floors with a passage to another building
deactivate UI

@enduml