@startuml

activate SPA
SPA -> GestaoInfoAPI : create(/api/pickUpAndDeliveryTasks)
activate GestaoInfoAPI

GestaoInfoAPI -> PickUpAndDeliveryTaskController : create
activate PickUpAndDeliveryTaskController

PickUpAndDeliveryTaskController -> PickUpAndDeliveryTaskService : createPickupAndDeliveryTask()
activate PickUpAndDeliveryTaskService

PickUpAndDeliveryTaskService -> pickUpAndDeliveryTask : create
PickUpAndDeliveryTaskService -> PickUpAndDeliveryTaskRepo : save(pickUpAndDeliveryTask)
activate PickUpAndDeliveryTaskRepo
PickUpAndDeliveryTaskRepo -> PickUpAndDeliveryTaskService : pickUpAndDeliveryTasks
deactivate PickUpAndDeliveryTaskRepo

PickUpAndDeliveryTaskService -> PickUpAndDeliveryTaskskMap : toDTO(pickUpAndDeliveryTasks)
activate PickUpAndDeliveryTaskskMap

PickUpAndDeliveryTaskskMap -> PickUpAndDeliveryTaskService : taskDTO
deactivate PickUpAndDeliveryTaskskMap

PickUpAndDeliveryTaskService -> PickUpAndDeliveryTaskController : taskDTO()

PickUpAndDeliveryTaskController -> GestaoInfoAPI : status code 201

GestaoInfoAPI -> SPA : Success

@enduml