@startuml
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US300

actor "User" as User
participant "UI" as UI

activate User
activate UI
User -> UI : 1 : requests building floors served by elevator
UI --> User : returns json with floors


@enduml