@startuml

activate SPA
SPA -> GestaoInfoAPI : patch(/api/requests)
activate GestaoInfoAPI

GestaoInfoAPI -> RequestController : patch
activate RequestController

RequestController -> RequestService : approveOrRejectRequest()
activate RequestService

RequestService -> Request : approve or reject
RequestService -> RequestRepo : save(request)
activate RequestRepo
RequestRepo -> RequestService : request
deactivate RequestRepo

RequestService -> RequestMap : toDTO(request)
activate RequestMap

RequestMap -> RequestService : requestDTO
deactivate RequestMap

RequestService -> RequestController : requestDTO()

RequestController -> GestaoInfoAPI : status code 201

GestaoInfoAPI -> SPA : Success

@enduml