@startuml

autonumber

activate User

User -> SPA : Asks to remove the systemUser and his data
activate SPA

SPA -> SystemUser : DELETE/ systemUser(email, password, roleId, phoneNumber, contribuinte)
activate SystemUser
SystemUser --> SPA : status code
deactivate SystemUser

alt successfull case
    SPA -> User: systemUser removed successfully
else failure
    SPA -> User: systemUser not removed
end


@enduml