@startuml

autonumber

Actor User
activate User
User -> SPA : Edit a building floor information
activate SPA

SPA --> User : requests data (buildingId, floorNumber)
deactivate SPA

User -> SPA : types data (buildingId, floorNumber)
activate SPA

SPA -> Floor : PUT/PATCH/ floor/{floorId, buildingId, floorNumber, description}
activate Floor

Floor --> SPA : status code
deactivate Floor

alt successfull case
    SPA --> User : floor edited successfully
else failure
    SPA --> User : floor not edited with success
end


@enduml