# .github/workflows/deploy.yml

name: Deploy to DEI VM

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm install
        working-directory: SEM_PI_23-24_G14/SPA

      - name: Build Angular application
        run: npm run build
        working-directory: SEM_PI_23-24_G14/SPA

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 11093
          username: root
          source: dist/spa/
          target: /var/www/html

      - name: SSH into server and restart web server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 11093
          username: root
          script: |
            sudo systemctl restart apache2 

