# .github/workflows/deploy.yml

name: Deploy to Linux VM

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Adjust version as needed

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build --prod

      - name: Copy files to server
        uses: appleboy/scp-action@v0.3.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist/spa/
          target: /var/www/html

      - name: SSH into server and restart web server
        uses: appleboy/ssh-action@v0.6.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/on/server/
            sudo systemctl restart apache2 

